export const types = {
    uuid: {
        hasDefault: false,
        hasPrecision: false,
        hasScale: false,
        hasLength: false,
        hasUnicode: false,
        hasNullable: true,
        hasAutoIncrement: false,
    },
    boolean: {
        hasDefault: true,
        hasPrecision: false,
        hasScale: false,
        hasLength: false,
        hasUnicode: false,
        hasNullable: true,
        hasAutoIncrement: false,
    },
    smallint: {
        hasDefault: true,
        hasPrecision: false,
        hasScale: false,
        hasLength: false,
        hasUnicode: false,
        hasNullable: true,
        hasAutoIncrement: true,
    },

    integer: {
        hasDefault: true,
        hasPrecision: false,
        hasScale: false,
        hasLength: false,
        hasUnicode: false,
        hasNullable: true,
        hasAutoIncrement: true,
    },
    largeint: {
        hasDefault: true,
        hasPrecision: false,
        hasScale: false,
        hasLength: false,
        hasUnicode: false,
        hasNullable: true,
        hasAutoIncrement: true,
    },
    float: {
        hasDefault: true,
        hasPrecision: true,
        hasScale: true,
        hasLength: false,
        hasUnicode: false,
        hasNullable: true,
        hasAutoIncrement: true,
    },
    double: {
        hasDefault: true,
        hasPrecision: false,
        hasScale: false,
        hasLength: false,
        hasUnicode: false,
        hasNullable: true,
        hasAutoIncrement: true,
    },
    number: {
        hasDefault: true,
        hasPrecision: false,
        hasScale: false,
        hasLength: false,
        hasUnicode: false,
        hasNullable: true,
        hasAutoIncrement: true,
    },
    string: {
        hasDefault: true,
        hasPrecision: false,
        hasScale: false,
        hasLength: true,
        hasUnicode: true,
        hasNullable: true,
        hasAutoIncrement: false,
    },
    text: {
        hasDefault: true,
        hasPrecision: false,
        hasScale: false,
        hasLength: false,
        hasUnicode: false,
        hasNullable: true,
        hasAutoIncrement: false,
    },
    time: {
        hasDefault: true,
        hasPrecision: false,
        hasScale: false,
        hasLength: false,
        hasUnicode: false,
        hasNullable: true,
        hasAutoIncrement: false,
    },
    date: {
        hasDefault: true,
        hasPrecision: false,
        hasScale: false,
        hasLength: false,
        hasUnicode: false,
        hasNullable: true,
        hasAutoIncrement: false,
    },
    datetime: {
        hasDefault: true,
        hasPrecision: false,
        hasScale: false,
        hasLength: false,
        hasUnicode: false,
        hasNullable: true,
        hasAutoIncrement: false,
    },
    timestamp: {
        hasDefault: true,
        hasPrecision: false,
        hasScale: false,
        hasLength: false,
        hasUnicode: false,
        hasNullable: true,
        hasAutoIncrement: false,
    },
    json: {
        hasDefault: true,
        hasPrecision: false,
        hasScale: false,
        hasLength: false,
        hasUnicode: false,
        hasNullable: true,
        hasAutoIncrement: false,
    },
    geometry: {
        hasDefault: true,
        hasPrecision: false,
        hasScale: false,
        hasLength: false,
        hasUnicode: false,
        hasNullable: true,
        hasAutoIncrement: false,
    },
    geography: {
        hasDefault: false,
        hasPrecision: false,
        hasScale: false,
        hasLength: false,
        hasUnicode: false,
        hasNullable: true,
        hasAutoIncrement: false,
    },
};

export type AttributeType = keyof typeof types;